import { Ticket, UserProfile, AppNotification } from "./types";

export const MOCK_USERS: UserProfile[] = [
  {
    uid: "user_employee_1",
    name: "Alex Rivera",
    email: "alex.rivera@company.com",
    role: "employee",
    createdAt: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
  },
  {
    uid: "user_employee_2",
    name: "Sarah Chen",
    email: "sarah.chen@company.com",
    role: "employee",
    createdAt: new Date(Date.now() - 25 * 24 * 3600 * 1000).toISOString(),
  },
  {
    uid: "user_staff_1",
    name: "David Kim",
    email: "david.kim@company.com",
    role: "staff",
    createdAt: new Date(Date.now() - 60 * 24 * 3600 * 1000).toISOString(),
  },
  {
    uid: "user_staff_2",
    name: "Elena Rostova",
    email: "elena.rostova@company.com",
    role: "staff",
    createdAt: new Date(Date.now() - 45 * 24 * 3600 * 1000).toISOString(),
  },
  {
    uid: "user_manager_1",
    name: "Marcus Vance",
    email: "marcus.vance@company.com",
    role: "manager",
    createdAt: new Date(Date.now() - 90 * 24 * 3600 * 1000).toISOString(),
  },
];

export const MOCK_TICKETS: Ticket[] = [
  {
    id: "MHL-101",
    title: "MacBook Pro display flickering constantly",
    description: "Whenever I connect to the external monitor via USB-C or even on standalone laptop screen, the display flickers violently. Need hardware inspection or replacement.",
    category: "Hardware",
    priority: "High",
    requesterId: "user_employee_1",
    requesterName: "Alex Rivera",
    requesterEmail: "alex.rivera@company.com",
    ownerId: "user_staff_1",
    ownerName: "David Kim",
    status: "In Progress",
    createdAt: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(), // 4 days ago -> OVERDUE in current status
    updatedAt: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
    stateHistory: [
      {
        status: "New",
        changedBy: "user_employee_1",
        changedByName: "Alex Rivera",
        changedAt: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
        note: "Ticket created",
      },
      {
        status: "Assigned",
        changedBy: "user_staff_1",
        changedByName: "David Kim",
        changedAt: new Date(Date.now() - 4 * 24 * 3600 * 1000 + 3600000).toISOString(),
        note: "Assigned to David Kim",
      },
      {
        status: "In Progress",
        changedBy: "user_staff_1",
        changedByName: "David Kim",
        changedAt: new Date(Date.now() - 4 * 24 * 3600 * 1000 + 7200000).toISOString(),
        note: "Diagnostics started",
      },
    ],
    comments: [
      {
        id: "comm_1",
        authorId: "user_staff_1",
        authorName: "David Kim",
        authorRole: "staff",
        text: "Ordered a replacement USB-C dongle to test if the port is damaged.",
        createdAt: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
        isInternal: true,
      },
    ],
  },
  {
    id: "MHL-102",
    title: "Need Production Database read-only access for Q3 Audit",
    description: "Preparing compliance report for SOC2 audit. Requesting temporary read-only credentials to the production analytics replica.",
    category: "Access",
    priority: "Urgent",
    requesterId: "user_employee_2",
    requesterName: "Sarah Chen",
    requesterEmail: "sarah.chen@company.com",
    ownerId: "user_staff_2",
    ownerName: "Elena Rostova",
    status: "Waiting on Requester",
    createdAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    stateHistory: [
      {
        status: "New",
        changedBy: "user_employee_2",
        changedByName: "Sarah Chen",
        changedAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
      },
      {
        status: "Assigned",
        changedBy: "user_staff_2",
        changedByName: "Elena Rostova",
        changedAt: new Date(Date.now() - 20 * 3600 * 1000).toISOString(),
      },
      {
        status: "In Progress",
        changedBy: "user_staff_2",
        changedByName: "Elena Rostova",
        changedAt: new Date(Date.now() - 18 * 3600 * 1000).toISOString(),
      },
      {
        status: "Waiting on Requester",
        changedBy: "user_staff_2",
        changedByName: "Elena Rostova",
        changedAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
        note: "Awaiting security manager approval signature",
      },
    ],
    comments: [
      {
        id: "comm_2",
        authorId: "user_staff_2",
        authorName: "Elena Rostova",
        authorRole: "staff",
        text: "Please attach the signed security clearance form so we can provision the IAM role.",
        createdAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
        isInternal: false,
      },
    ],
  },
  {
    id: "MHL-103",
    title: "VPN connection dropping every 15 minutes",
    description: "GlobalProtect client disconnects repeatedly when connecting to US-East gateway. Logs indicate session timeout.",
    category: "Network",
    priority: "Medium",
    requesterId: "user_employee_1",
    requesterName: "Alex Rivera",
    requesterEmail: "alex.rivera@company.com",
    ownerId: null,
    ownerName: null,
    status: "New",
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    stateHistory: [
      {
        status: "New",
        changedBy: "user_employee_1",
        changedByName: "Alex Rivera",
        changedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
      },
    ],
    comments: [],
  },
  {
    id: "MHL-104",
    title: "Figma enterprise license seat provisioning",
    description: "Joined the Product Design squad this week and need full editor access on Figma.",
    category: "Software",
    priority: "Low",
    requesterId: "user_employee_2",
    requesterName: "Sarah Chen",
    requesterEmail: "sarah.chen@company.com",
    ownerId: "user_staff_1",
    ownerName: "David Kim",
    status: "Resolved",
    createdAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    stateHistory: [
      {
        status: "New",
        changedBy: "user_employee_2",
        changedByName: "Sarah Chen",
        changedAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
      },
      {
        status: "Assigned",
        changedBy: "user_staff_1",
        changedByName: "David Kim",
        changedAt: new Date(Date.now() - 36 * 3600 * 1000).toISOString(),
      },
      {
        status: "In Progress",
        changedBy: "user_staff_1",
        changedByName: "David Kim",
        changedAt: new Date(Date.now() - 30 * 3600 * 1000).toISOString(),
      },
      {
        status: "Resolved",
        changedBy: "user_staff_1",
        changedByName: "David Kim",
        changedAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
        note: "Invited to organization workspace via Okta SSO",
      },
    ],
    comments: [],
  },
  {
    id: "MHL-105",
    title: "Zoom Rooms AV audio echo in Conference Room 4B",
    description: "Microphone feedback loop occurring during hybrid meetings.",
    category: "Hardware",
    priority: "Medium",
    requesterId: "user_employee_1",
    requesterName: "Alex Rivera",
    requesterEmail: "alex.rivera@company.com",
    ownerId: "user_staff_2",
    ownerName: "Elena Rostova",
    status: "Closed",
    createdAt: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 24 * 3600 * 1000).toISOString(),
    stateHistory: [
      {
        status: "New",
        changedBy: "user_employee_1",
        changedByName: "Alex Rivera",
        changedAt: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
      },
      {
        status: "Assigned",
        changedBy: "user_staff_2",
        changedByName: "Elena Rostova",
        changedAt: new Date(Date.now() - 9 * 24 * 3600 * 1000).toISOString(),
      },
      {
        status: "In Progress",
        changedBy: "user_staff_2",
        changedByName: "Elena Rostova",
        changedAt: new Date(Date.now() - 9 * 24 * 3600 * 1000).toISOString(),
      },
      {
        status: "Resolved",
        changedBy: "user_staff_2",
        changedByName: "Elena Rostova",
        changedAt: new Date(Date.now() - 8 * 24 * 3600 * 1000).toISOString(),
        note: "DSP soundbar firmware updated and recalibrated",
      },
      {
        status: "Closed",
        changedBy: "user_employee_1",
        changedByName: "Alex Rivera",
        changedAt: new Date(Date.now() - 8 * 24 * 3600 * 1000).toISOString(),
        note: "Confirmed audio issue resolved",
      },
    ],
    comments: [],
  },
];

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: "notif_1",
    userId: "user_employee_2",
    ticketId: "MHL-104",
    ticketTitle: "Figma enterprise license seat provisioning",
    type: "resolved",
    message: "Your ticket MHL-104 has been marked as Resolved by David Kim.",
    read: false,
    createdAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
  },
  {
    id: "notif_2",
    userId: "user_staff_1",
    ticketId: "MHL-101",
    ticketTitle: "MacBook Pro display flickering constantly",
    type: "assigned",
    message: "Ticket MHL-101 was assigned to you.",
    read: true,
    createdAt: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
  },
];
